{% set name = "gifsicle" %}
{% set version = "1.96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kohler/gifsicle/archive/v{{ version }}.tar.gz
  sha256: 1104b338745f466bdb6b739b152c42a5dfe2fb50a4c21e3bcd78446766f007ea

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

test:
  commands:
    - gifsicle --help

about:
  home: http://www.lcdf.org/gifsicle/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Create, manipulate, and optimize GIF images and animations

  description: |
    Gifsicle manipulates GIF image files. Depending on command line 
    options, it can merge several GIFs into a GIF animation; explode 
    an animation into its component frames; change individual frames 
    in an animation; turn interlacing on and off; add transparency; add 
    delays, disposals, and looping to animations; add and remove comments; 
    flip and rotate; optimize animations for space; change images' 
    colormaps; and other things.
  doc_url: http://www.lcdf.org/gifsicle/
  dev_url: https://github.com/kohler/gifsicle

extra:
  recipe-maintainers:
    - jan-janssen
